[gcp_service_account]
type = "service_account"
project_id = "dogwood-outcome-443507-d4"
private_key_id = "d2564b55216272817b5d9dece23ee79fa2423949"
private_key = "-----BEGIN PRIVATE KEY-----\\nMIIEvQIBADANBgkqhkiG...中略...\\n-----END PRIVATE KEY-----\\n"
client_email = "streamlit@dogwood-outcome-443507-d4.iam.gserviceaccount.com"
client_id = "106761451176673690975"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit%40dogwood-outcome-443507-d4.iam.gserviceaccount.com"
